apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 1
  # --- DIT STUKJE MISTE ---
  selector:
    matchLabels:
      app: weather-app
  # ------------------------
  template:
    metadata:
      labels:
        app: weather-app # Dit moet matchen met de selector hierboven!
    spec:
      automountServiceAccountToken: false
      containers:
        - name: weather-app
          image: mkwaak/weather-app-main:2.1.x
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
